const fs=require('fs');
const path=require('path');
const https=require('https');
const crypto=require('crypto');
const AdmZip=require('adm-zip');
const FOLDERS=['mods','config','resourcepacks','datapacks','essential','fancymenu_data','shaderpacks'];
function fetchBuffer(url,max){return new Promise((resolve,reject)=>{const r=https.get(url,{headers:{'User-Agent':'Steampunk-SMP-Launcher'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return resolve(fetchBuffer(new URL(res.headers.location,url).toString(),max));}if(res.statusCode!==200){res.resume();return reject(new Error('HTTP '+res.statusCode));}const a=[];let n=0;res.on('data',c=>{n+=c.length;if(n>max)return r.destroy(new Error('Response too large'));a.push(c);});res.on('end',()=>resolve(Buffer.concat(a)));res.on('error',reject)});r.on('error',reject);r.setTimeout(30000,()=>r.destroy(new Error('Network timeout')))});}
async function fetchManifest(url){const b=await fetchBuffer(url,1048576);return JSON.parse(b.toString('utf8'));}
function sha256(file){return new Promise((resolve,reject)=>{const h=crypto.createHash('sha256');const s=fs.createReadStream(file);s.on('data',c=>h.update(c));s.on('error',reject);s.on('end',()=>resolve(h.digest('hex')));});}
function download(url,dest,expected,progress){return new Promise((resolve,reject)=>{fs.mkdirSync(path.dirname(dest),{recursive:true});const tmp=dest+'.download';const r=https.get(url,{headers:{'User-Agent':'Steampunk-SMP-Launcher'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return resolve(download(new URL(res.headers.location,url).toString(),dest,expected,progress));}if(res.statusCode!==200){res.resume();return reject(new Error('Modpack download failed (HTTP '+res.statusCode+').'));}const total=Number(res.headers['content-length']||0);let done=0;const out=fs.createWriteStream(tmp);res.on('data',c=>{done+=c.length;if(progress)progress(total?Math.round(done/total*100):0,done,total)});res.pipe(out);out.on('finish',async()=>{try{out.close();if(expected){const actual=await sha256(tmp);if(actual.toLowerCase()!==expected.toLowerCase())throw new Error('Modpack SHA-256 controle mislukt.')}fs.renameSync(tmp,dest);resolve()}catch(e){fs.rmSync(tmp,{force:true});reject(e)}});out.on('error',reject)});r.on('error',reject);r.setTimeout(120000,()=>r.destroy(new Error('Modpack download timeout')))})}
function extractSafe(zip,dest){const z=new AdmZip(zip);const root=path.resolve(dest)+path.sep;for(const e of z.getEntries()){if(e.isDirectory)continue;const t=path.resolve(dest,e.entryName);if(!t.startsWith(root))throw new Error('Onveilige ZIP-inhoud geblokkeerd.')}z.extractAllTo(dest,true)}
async function sync(era,baseDir,manifest,emit){const version=manifest.latestVersion||manifest.version;const info=manifest.versions&&manifest.versions[version];if(!version||!info||!info.url)return;const state=path.join(baseDir,'.installed-version');const installed=fs.existsSync(state)?fs.readFileSync(state,'utf8').trim():'';if(installed===version)return;if(emit)emit('modpack-start',{version,installedVersion:installed});const archive=path.join(baseDir,'.downloads',version+'.zip');await download(info.url,archive,info.sha256||null,(p,d,t)=>emit&&emit('modpack-progress',{percent:p,downloaded:d,total:t}));const tmp=path.join(baseDir,'.update-extracted');fs.rmSync(tmp,{recursive:true,force:true});fs.mkdirSync(tmp,{recursive:true});try{extractSafe(archive,tmp);const source=fs.existsSync(path.join(tmp,'mods'))?tmp:(fs.existsSync(path.join(tmp,'overrides'))?path.join(tmp,'overrides'):tmp);for(const f of FOLDERS){const from=path.join(source,f),to=path.join(baseDir,f);if(fs.existsSync(from)){fs.mkdirSync(to,{recursive:true});fs.cpSync(from,to,{recursive:true,force:true})}}fs.writeFileSync(state,version,'utf8')}finally{fs.rmSync(tmp,{recursive:true,force:true})}if(emit)emit('modpack-ready',{version})}
module.exports={fetchManifest,sync};
